on:
  workflow_dispatch:

name: main
jobs:
  libraries:
    name: Library
    runs-on: windows-2022

    permissions:
      id-token: write
      contents: read
      packages: read

    strategy:
      fail-fast: false
      matrix:
        libraryName: [Core, AvaloniaMediaImaging, SystemDrawing, SystemWindowsMedia]

    steps:

    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-tags: true

    - name: Install dependencies
      run: ./install.dependencies.cmd
      working-directory: build/windows

    - name: Create nuget.config
      run: './create-nuget-config.cmd "dlemstra" "${{ secrets.GITHUB_TOKEN }}"'
      working-directory: src/Magick.Native

    - name: Install Magick.Native
      run: ./install.cmd
      working-directory: src/Magick.Native

    - name: 'Build Magick.NET.${{ matrix.libraryName }} (Release)'
      run: './build.Magick.NET.cmd "Q8" "Any CPU" Release'
      working-directory: build/windows

    - name: Set NuGet version
      run: ./set.version.ps1
      working-directory: publish

    - name: Create NuGet package
      run: './publish.library.cmd "Magick.NET.${{ matrix.libraryName }}"'
      working-directory: publish

    - name: Upload library
      uses: actions/upload-artifact@v4
      with:
        name: 'Magick.NET.${{ matrix.libraryName }}'
        path: publish/output
